### ISSUE TITLE
在window上会出现错误

### ISSUE THREAD

**Issue by Oct1a** [axolo/node-wechat-pay#1]
```
const WechatPay = require('@axolo/node-wechat-pay');
const fs = require('fs')

const wechatPay = new WechatPay({
  appId: payConfig.wx.appId,
  mchId: payConfig.wx.mchid,
  mchCertSn: payConfig.wx.serial_no,
  mchCertKey: fs.readFileSync(payConfig.wx.private_key),
  mchCert: fs.readFileSync(payConfig.wx.private_cert_key),
  apiV3Key: payConfig.wx.apiv3_private_key,
  notifyUrl:  payConfig.wx.notify_url,
});
```
相同的配置在服务器(centos)上是可以运行的，但本地调试会出错,，我想可能是openssl的问题，但不知道怎么解决

```
Error: error:25078067:DSO support routines:win32_load:could not load the shared library
    at Sign.sign (internal/crypto/sig.js:110:29)
    at WechatPay.createSign (D:\cloud_script\admin_server\node_modules\_@axolo_node-wechat-pay@0.3.5@@axolo\node-wechat-pay\src\index.js:115:17)
    at WechatPay.signature (D:\cloud_script\admin_server\node_modules\_@axolo_node-wechat-pay@0.3.5@@axolo\node-wechat-pay\src\index.js:162:28)
    at WechatPay.authorization (D:\cloud_script\admin_server\node_modules\_@axolo_node-wechat-pay@0.3.5@@axolo\node-wechat-pay\src\index.js:176:23)
    at D:\cloud_script\admin_server\node_modules\_@axolo_node-wechat-pay@0.3.5@@axolo\node-wechat-pay\src\index.js:33:34
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  opensslErrorStack: [
    'error:0E076071:configuration file routines:module_run:unknown module name',
    'error:0E07506E:configuration file routines:module_load_dso:error loading dso',
    'error:25070067:DSO support routines:DSO_load:could not load the shared library'
  ],
  library: 'DSO support routines',
  function: 'win32_load',
  reason: 'could not load the shared library',
  code: 'ERR_OSSL_DSO_COULD_NOT_LOAD_THE_SHARED_LIBRARY'
}
```

![](http://img.oct1a.cn/202201271039984.png)

**Comment by axolo** [comment]
正确安装 openssl 即可，安装后在命令行中输入 openssl 测试一下看看命令是否正确。
如果你安装了git，那么把 “Git安装目录\usr\bin" 加入系统环境变量 PATH 试一下。
